# Generated by Django 4.1.7 on 2023-02-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='incident_id',
            field=models.CharField(default='RMG*****202391633', max_length=15, unique=True),
        ),
    ]
