# Generated by Django 4.1.7 on 2023-02-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_incidents_incident_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='incident_id',
            field=models.CharField(default='RMG*****202336885', max_length=15, unique=True),
        ),
    ]
