# Generated by Django 4.1.7 on 2023-02-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_incidents_incident_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidents',
            name='id',
        ),
        migrations.AlterField(
            model_name='incidents',
            name='incident_id',
            field=models.CharField(auto_created=True, default='RMG202329970', editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
