# Generated by Django 4.1.7 on 2023-02-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_alter_incidents_id_alter_incidents_incident_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='incident_id',
            field=models.CharField(auto_created=True, default='RMG645382023', editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='reporter_name',
            field=models.CharField(max_length=60),
        ),
    ]
