# Generated by Django 4.1.7 on 2023-02-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_alter_incidents_incident_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidents',
            name='incident_id',
        ),
    ]
