# Generated by Django 4.1.7 on 2023-02-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_remove_incidents_incident_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='incident_id',
            field=models.CharField(default='RMG391162023', editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='id',
            field=models.CharField(auto_created=True, max_length=1, primary_key=True, serialize=False),
        ),
    ]
