# Generated by Django 4.1.7 on 2023-02-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_incidents_incident_id_alter_incidents_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidents',
            name='id',
        ),
        migrations.AlterField(
            model_name='incidents',
            name='incident_id',
            field=models.CharField(default='RMG202379479', editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
