# Generated by Django 4.1.7 on 2023-02-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_remove_incidents_id_alter_incidents_incident_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='incident_id',
            field=models.CharField(default='RMG202399901', editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
