# Generated by Django 4.1.7 on 2023-03-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_alter_incidents_incident_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='id',
            field=models.IntegerField(auto_created=True, default=None, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='incident_id',
            field=models.CharField(default='RMG202301666', editable=False, max_length=15),
        ),
    ]
